const cropCalendar = [
  // ANDHRA PRADESH
  { crop: 'Rice', season: 'kharif', region: 'Coastal Andhra', state: 'Andhra Pradesh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'November', harvestingEnd: 'December', duration: 135, growingTips: ['Use SRI method for higher yields', 'Maintain 5cm water depth during vegetative stage', 'Apply zinc sulphate 25kg/ha at nursery'], waterRequirement: 'high', soilType: ['Clay loam', 'Alluvial', 'Laterite'], temperature: { min: 20, max: 35 }, rainfall: { min: 1000, max: 1500 }, festivals: [{ name: 'Sankranti', date: 'January 14', description: 'Harvest festival celebrated with new rice' }] },
  { crop: 'Rice', season: 'rabi', region: 'Coastal Andhra', state: 'Andhra Pradesh', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'March', harvestingEnd: 'April', duration: 120, growingTips: ['Use short duration varieties', 'Ensure irrigation facility', 'Monitor for BPH pests'], waterRequirement: 'high', soilType: ['Clay loam', 'Alluvial'], temperature: { min: 18, max: 32 }, rainfall: { min: 200, max: 400 } },
  { crop: 'Groundnut', season: 'kharif', region: 'Rayalaseema', state: 'Andhra Pradesh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 110, growingTips: ['Apply gypsum at pegging stage', 'Use TMV-2 variety', 'Maintain plant population of 3.33 lakh/ha'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Red loamy'], temperature: { min: 22, max: 35 }, rainfall: { min: 500, max: 800 } },
  { crop: 'Cotton', season: 'kharif', region: 'Guntur', state: 'Andhra Pradesh', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'December', harvestingEnd: 'February', duration: 210, growingTips: ['Use Bt cotton hybrids', 'Follow RDF 120:60:60 NPK', 'Monitor for pink bollworm'], waterRequirement: 'medium', soilType: ['Black cotton', 'Red sandy loam'], temperature: { min: 22, max: 40 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Chilli', season: 'kharif', region: 'Guntur', state: 'Andhra Pradesh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'January', duration: 210, growingTips: ['Gundu Suddalu variety for high yield', 'Drip irrigation recommended', 'Stake plants for better growth'], waterRequirement: 'medium', soilType: ['Red loamy', 'Black clay'], temperature: { min: 20, max: 35 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Maize', season: 'rabi', region: 'Coastal Andhra', state: 'Andhra Pradesh', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 120, growingTips: ['Use hybrid seeds', 'Line sowing at 60x25cm', 'Top dressing at 30 DAS'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 18, max: 32 }, rainfall: { min: 400, max: 700 } },

  // TELANGANA
  { crop: 'Rice', season: 'kharif', region: 'Telangana', state: 'Telangana', sowingStart: 'June', sowingEnd: 'August', harvestingStart: 'November', harvestingEnd: 'January', duration: 135, growingTips: ['Use Telangana Sona variety', 'Delay nursery if heavy rains', 'Apply potash at panicle initiation'], waterRequirement: 'high', soilType: ['Red laterite', 'Black clay'], temperature: { min: 20, max: 38 }, rainfall: { min: 800, max: 1200 }, festivals: [{ name: 'Bonalu', date: 'July', description: 'Thanksgiving festival before kharif harvest' }] },
  { crop: 'Cotton', season: 'kharif', region: 'Telangana', state: 'Telangana', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'December', harvestingEnd: 'March', duration: 210, growingTips: ['Nuziveedu seeds high yielding', 'Deep plowing before sowing', 'Install pheromone traps for pink bollworm'], waterRequirement: 'medium', soilType: ['Black cotton', 'Red sandy'], temperature: { min: 22, max: 42 }, rainfall: { min: 600, max: 900 } },
  { crop: 'Maize', season: 'kharif', region: 'Telangana', state: 'Telangana', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 100, growingTips: ['PMH 1 or DHM 117 varieties', 'Apply 150:60:50 NPK', 'Weed control with atrazine'], waterRequirement: 'medium', soilType: ['Red sandy loam', 'Black soil'], temperature: { min: 20, max: 36 }, rainfall: { min: 500, max: 900 } },
  { crop: 'Turmeric', season: 'kharif', region: 'Nizamabad', state: 'Telangana', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'January', harvestingEnd: 'February', duration: 240, growingTips: ['Nizamabad town famous for turmeric', 'Provide shade for better growth', 'Apply well-decomposed FYM 25t/ha'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Black soil'], temperature: { min: 20, max: 35 }, rainfall: { min: 800, max: 1200 } },
  { crop: 'Sugarcane', season: 'kharif', region: 'Telangana', state: 'Telangana', sowingStart: 'January', sowingEnd: 'February', harvestingStart: 'December', harvestingEnd: 'February', duration: 365, growingTips: ['Set treatment with fungicide', 'Ridge and furrow planting', 'Earthing up at 120 days'], waterRequirement: 'high', soilType: ['Clay loam', 'Black soil'], temperature: { min: 20, max: 38 }, rainfall: { min: 800, max: 1200 } },

  // MAHARASHTRA
  { crop: 'Sugarcane', season: 'kharif', region: 'Western Maharashtra', state: 'Maharashtra', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'October', harvestingEnd: 'December', duration: 400, growingTips: ['Co 86032 variety recommended', 'Drip irrigation for water saving', 'Trash mulching for moisture retention'], waterRequirement: 'high', soilType: ['Black deep soil', 'Medium black'], temperature: { min: 20, max: 38 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Cotton', season: 'kharif', region: 'Vidarbha', state: 'Maharashtra', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'December', harvestingEnd: 'February', duration: 200, growingTips: ['Bt cotton preferred', 'Neem cake application reduces nematodes', 'Five light irrigations during dry spells'], waterRequirement: 'low', soilType: ['Black cotton'], temperature: { min: 22, max: 42 }, rainfall: { min: 600, max: 900 } },
  { crop: 'Soybean', season: 'kharif', region: 'Marathwada', state: 'Maharashtra', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 105, growingTips: ['JS-335 and MAUS-71 varieties', 'Seed treatment with Rhizobium', 'Apply phosphorus 60kg/ha'], waterRequirement: 'medium', soilType: ['Medium black', 'Deep black'], temperature: { min: 20, max: 35 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Onion', season: 'rabi', region: 'Nashik', state: 'Maharashtra', sowingStart: 'December', sowingEnd: 'January', harvestingStart: 'April', harvestingEnd: 'May', duration: 130, growingTips: ['Nashik red variety famous', 'Raised bed nursery', 'Stop irrigation 15 days before harvest'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Red loam'], temperature: { min: 15, max: 32 }, rainfall: { min: 400, max: 700 } },
  { crop: 'Grapes', season: 'rabi', region: 'Nashik', state: 'Maharashtra', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'March', harvestingEnd: 'April', duration: 160, growingTips: ['Thompson Seedless variety', 'Pruning in October', 'GAP certification for export'], waterRequirement: 'medium', soilType: ['Well-drained sandy loam'], temperature: { min: 15, max: 35 }, rainfall: { min: 400, max: 700 } },
  { crop: 'Pearl Millet (Bajra)', season: 'kharif', region: 'Western Maharashtra', state: 'Maharashtra', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 110, growingTips: ['Drought tolerant crop', 'Line sowing at 45x15cm', 'Low fertilizer requirement'], waterRequirement: 'low', soilType: ['Sandy loam', 'Light sandy'], temperature: { min: 25, max: 40 }, rainfall: { min: 300, max: 600 } },

  // KARNATAKA
  { crop: 'Rice', season: 'kharif', region: 'Coastal Karnataka', state: 'Karnataka', sowingStart: 'June', sowingEnd: 'August', harvestingStart: 'November', harvestingEnd: 'January', duration: 140, growingTips: ['Coastal varieties: MO-1, MO-2', 'Apply potash 40kg/ha', 'Fish meal as organic source'], waterRequirement: 'high', soilType: ['Laterite', 'Clay loam'], temperature: { min: 20, max: 34 }, rainfall: { min: 2000, max: 4000 } },
  { crop: 'Ragi (Finger Millet)', season: 'kharif', region: 'Southern Karnataka', state: 'Karnataka', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 120, growingTips: ['Nutritious millet', 'Less water requiring crop', 'Good for rainfed conditions'], waterRequirement: 'low', soilType: ['Red loamy', 'Sandy loam'], temperature: { min: 18, max: 32 }, rainfall: { min: 400, max: 700 } },
  { crop: 'Coffee', season: 'kharif', region: 'Kodagu', state: 'Karnataka', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'November', harvestingEnd: 'January', duration: 365, growingTips: ['Arabica and Robusta varieties', 'Shade grown with silver oak', 'Prune after harvest'], waterRequirement: 'medium', soilType: ['Well-drained laterite', 'Red volcanic'], temperature: { min: 15, max: 28 }, rainfall: { min: 1500, max: 2500 } },
  { crop: 'Arecanut', season: 'all', region: 'Coastal Karnataka', state: 'Karnataka', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'November', harvestingEnd: 'February', duration: 365, growingTips: ['Perennial crop', 'Regular irrigation required', 'Proper fertilizer management'], waterRequirement: 'high', soilType: ['Deep well-drained loam'], temperature: { min: 15, max: 35 }, rainfall: { min: 2000, max: 3500 } },
  { crop: 'Sunflower', season: 'rabi', region: 'Northern Karnataka', state: 'Karnataka', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 110, growingTips: ['Morden hybrid varieties', 'Bee hives for pollination', 'Fertilizer 60:40:20 NPK'], waterRequirement: 'medium', soilType: ['Black', 'Red loamy'], temperature: { min: 15, max: 35 }, rainfall: { min: 300, max: 600 } },

  // TAMIL NADU
  { crop: 'Rice', season: 'kharif', region: 'Cauvery Delta', state: 'Tamil Nadu', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 120, growingTips: ['BPT-5204 and CR-1009 varieties', 'Delta region - traditional kuruvai season', 'Maintain 2-5cm water'], waterRequirement: 'high', soilType: ['Alluvial clay', 'Deltaic alluvium'], temperature: { min: 22, max: 38 }, rainfall: { min: 600, max: 1200 }, festivals: [{ name: 'Pongal', date: 'January 15', description: 'Harvest festival celebrating rice' }] },
  { crop: 'Rice', season: 'rabi', region: 'Cauvery Delta', state: 'Tamil Nadu', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 130, growingTips: ['Thaladi season - October to February', 'Use short duration 120-day varieties', 'Stem borer management critical'], waterRequirement: 'high', soilType: ['Alluvial clay'], temperature: { min: 20, max: 34 }, rainfall: { min: 300, max: 600 } },
  { crop: 'Coconut', season: 'all', region: 'Coastal Tamil Nadu', state: 'Tamil Nadu', sowingStart: 'June', sowingEnd: 'August', harvestingStart: 'Year-round', harvestingEnd: 'Year-round', duration: 365, growingTips: ['Tall and Dwarf varieties', 'Apply 10kg FYM + 1kg neem cake per palm', 'Remove dried leaves periodically'], waterRequirement: 'medium', soilType: ['Coastal sandy loam', 'Red laterite'], temperature: { min: 22, max: 38 }, rainfall: { min: 1000, max: 2000 } },
  { crop: 'Sugarcane', season: 'kharif', region: 'Tamil Nadu', state: 'Tamil Nadu', sowingStart: 'January', sowingEnd: 'February', harvestingStart: 'January', harvestingEnd: 'February', duration: 365, growingTips: ['Co 86032 and Co 99004 varieties', 'Drip fertigation saves 40% water', 'Trash mulching beneficial'], waterRequirement: 'high', soilType: ['Red loam', 'Black soil'], temperature: { min: 20, max: 38 }, rainfall: { min: 800, max: 1200 } },
  { crop: 'Banana', season: 'all', region: 'Tamil Nadu', state: 'Tamil Nadu', sowingStart: 'February', sowingEnd: 'April', harvestingStart: 'December', harvestingEnd: 'February', duration: 365, growingTips: ['Grand Naine variety for export', 'Tissue culture plants recommended', 'Drip irrigation with fertigation'], waterRequirement: 'high', soilType: ['Well-drained deep loam'], temperature: { min: 18, max: 35 }, rainfall: { min: 800, max: 1500 } },
  { crop: 'Groundnut', season: 'kharif', region: 'Tamil Nadu', state: 'Tamil Nadu', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 105, growingTips: ['TMV-7 and VRI-2 varieties', 'Apply gypsum 400kg/ha at pegging', 'Irrigate at 7-day intervals'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Red loam'], temperature: { min: 20, max: 35 }, rainfall: { min: 500, max: 800 } },
  { crop: 'Cotton', season: 'kharif', region: 'Tamil Nadu', state: 'Tamil Nadu', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'December', harvestingEnd: 'February', duration: 210, growingTips: ['Surabhi and MCU-7 varieties', 'Install pheromone traps', '88:44:44 NPK recommendation'], waterRequirement: 'medium', soilType: ['Black loam', 'Red sandy'], temperature: { min: 22, max: 40 }, rainfall: { min: 500, max: 900 } },

  // UTTAR PRADESH
  { crop: 'Wheat', season: 'rabi', region: 'Western UP', state: 'Uttar Pradesh', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'March', harvestingEnd: 'April', duration: 140, growingTips: ['HD-3086 and PBW-725 varieties', 'Zero tillage for early sowing', 'Four to five irrigations needed'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Clay loam', 'Alluvial'], temperature: { min: 10, max: 32 }, rainfall: { min: 200, max: 500 }, festivals: [{ name: 'Baisakhi', date: 'April 13', description: 'Wheat harvest festival' }] },
  { crop: 'Wheat', season: 'rabi', region: 'Eastern UP', state: 'Uttar Pradesh', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'April', harvestingEnd: 'May', duration: 145, growingTips: ['Use timely sowing varieties', 'Yield potential 50-55 q/ha', 'Weed management with isoproturon'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Alluvial'], temperature: { min: 8, max: 32 }, rainfall: { min: 300, max: 600 } },
  { crop: 'Rice', season: 'kharif', region: 'Eastern UP', state: 'Uttar Pradesh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 125, growingTips: ['Swarna and Sarjoo-52 varieties', 'Heavy rainfall area - avoid waterlogging', 'Urea 3 splits'], waterRequirement: 'high', soilType: ['Clay loam', 'Alluvial'], temperature: { min: 22, max: 38 }, rainfall: { min: 1000, max: 1500 } },
  { crop: 'Sugarcane', season: 'kharif', region: 'Western UP', state: 'Uttar Pradesh', sowingStart: 'February', sowingEnd: 'March', harvestingStart: 'January', harvestingEnd: 'February', duration: 365, growingTips: ['Co-0238 and Co-0118 varieties', 'Ridge planting method', 'Three earthing up operations'], waterRequirement: 'high', soilType: ['Clay loam', 'Deep alluvial'], temperature: { min: 18, max: 40 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Potato', season: 'rabi', region: 'Western UP', state: 'Uttar Pradesh', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'January', harvestingEnd: 'February', duration: 90, growingTips: ['Kufri Bahar and Kufri Pukhraj', 'Well-drained sandy loam best', 'Stop irrigation 2 weeks before harvest'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 10, max: 28 }, rainfall: { min: 200, max: 400 } },
  { crop: 'Mustard', season: 'rabi', region: 'Eastern UP', state: 'Uttar Pradesh', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 130, growingTips: ['Varuna and Pusa Gold varieties', 'Line sowing at 45x15cm', 'Apply sulfur 20kg/ha for oil content'], waterRequirement: 'low', soilType: ['Sandy loam', 'Loam'], temperature: { min: 8, max: 30 }, rainfall: { min: 200, max: 400 } },
  { crop: 'Maize', season: 'kharif', region: 'Western UP', state: 'Uttar Pradesh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 100, growingTips: ['DKC 9108 and P 3522 hybrids', 'Seed treatment with fungicide', 'Top dressing of urea 30 days after sowing'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 18, max: 35 }, rainfall: { min: 500, max: 900 } },
  { crop: 'Arhar (Pigeonpea)', season: 'kharif', region: 'Central UP', state: 'Uttar Pradesh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'January', harvestingEnd: 'February', duration: 210, growingTips: ['Bahar and UPAS-120 varieties', 'Intercrop with urd/moong', 'Drainage management critical'], waterRequirement: 'low', soilType: ['Sandy loam', 'Loam'], temperature: { min: 18, max: 36 }, rainfall: { min: 400, max: 800 } },

  // PUNJAB
  { crop: 'Wheat', season: 'rabi', region: 'Punjab', state: 'Punjab', sowingStart: 'November', sowingEnd: 'November', harvestingStart: 'April', harvestingEnd: 'April', duration: 150, growingTips: ['PBW-725, HD-3086 popular', 'Zero tillage after paddy', 'First irrigation at 21 days - CRI stage'], waterRequirement: 'medium', soilType: ['Alluvial sandy loam', 'Loam'], temperature: { min: 8, max: 32 }, rainfall: { min: 200, max: 500 }, festivals: [{ name: 'Baisakhi', date: 'April 13', description: 'Celebrates wheat harvest' }] },
  { crop: 'Rice', season: 'kharif', region: 'Punjab', state: 'Punjab', sowingStart: 'June', sowingEnd: 'June', harvestingStart: 'October', harvestingEnd: 'October', duration: 130, growingTips: ['PR-126 and Pusa-44 varieties', 'Delay transplanting to save water', 'Direct seeding alternative to puddling'], waterRequirement: 'high', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 20, max: 40 }, rainfall: { min: 400, max: 700 } },
  { crop: 'Cotton', season: 'kharif', region: 'Southwest Punjab', state: 'Punjab', sowingStart: 'April', sowingEnd: 'May', harvestingStart: 'October', harvestingEnd: 'December', duration: 200, growingTips: ['Bt cotton hybrids', 'Whitefly management critical', 'Follow PAU recommendations'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 20, max: 45 }, rainfall: { min: 200, max: 500 } },
  { crop: 'Maize', season: 'kharif', region: 'Punjab', state: 'Punjab', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'September', harvestingEnd: 'October', duration: 105, growingTips: ['PMH-10 and DKC hybrid varieties', 'Baby corn has good export potential', 'Integrated pest management for stem borer'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 18, max: 36 }, rainfall: { min: 400, max: 700 } },
  { crop: 'Sugarcane', season: 'kharif', region: 'Punjab', state: 'Punjab', sowingStart: 'February', sowingEnd: 'March', harvestingStart: 'January', harvestingEnd: 'February', duration: 360, growingTips: ['CoJ-88 and Co-238 varieties', 'Ridge planting for better drainage', 'Earthing up at tillering stage'], waterRequirement: 'high', soilType: ['Clay loam', 'Loam'], temperature: { min: 15, end: 42 }, rainfall: { min: 500, max: 800 } },

  // HARYANA
  { crop: 'Wheat', season: 'rabi', region: 'Haryana', state: 'Haryana', sowingStart: 'November', sowingEnd: 'November', harvestingStart: 'April', harvestingEnd: 'April', duration: 150, growingTips: ['HD-2967, PBW-502 varieties', 'CRI irrigation at 21 days critical', 'Terminal heat tolerance needed'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 8, max: 34 }, rainfall: { min: 200, max: 500 } },
  { crop: 'Rice', season: 'kharif', region: 'Haryana', state: 'Haryana', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 130, growingTips: ['Basmati varieties for export', 'Pusa Basmati-1121 and 1509', 'Direct seeding in rainfed areas'], waterRequirement: 'high', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 20, max: 40 }, rainfall: { min: 300, max: 600 } },
  { crop: 'Mustard', season: 'rabi', region: 'Haryana', state: 'Haryana', sowingStart: 'October', sowingEnd: 'October', harvestingStart: 'February', harvestingEnd: 'March', duration: 130, growingTips: ['RH-406 and RH-781 varieties', 'Line sowing at 45cm spacing', 'Control aphids with dimethoate'], waterRequirement: 'low', soilType: ['Sandy loam', 'Loam'], temperature: { min: 5, max: 30 }, rainfall: { min: 200, max: 400 } },
  { crop: 'Cotton', season: 'kharif', region: 'Haryana', state: 'Haryana', sowingStart: 'April', sowingEnd: 'May', harvestingStart: 'October', harvestingEnd: 'December', duration: 195, growingTips: ['Bt cotton varieties', 'Spacing 67.5x60cm', 'Pink bollworm management'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 20, max: 45 }, rainfall: { min: 200, max: 500 } },

  // RAJASTHAN
  { crop: 'Pearl Millet (Bajra)', season: 'kharif', region: 'Rajasthan', state: 'Rajasthan', sowingStart: 'July', sowingEnd: 'August', harvestingStart: 'October', harvestingEnd: 'November', duration: 90, growingTips: ['HHB-67 and RHB-177 varieties', 'Drought tolerant - grows in 300mm rainfall', 'Stagger sowing for fodder'], waterRequirement: 'low', soilType: ['Sandy', 'Sandy loam'], temperature: { min: 25, max: 45 }, rainfall: { min: 200, max: 500 } },
  { crop: 'Mustard', season: 'rabi', region: 'Rajasthan', state: 'Rajasthan', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 130, growingTips: ['Rajasthan is India\'s top mustard producer', 'Laxmi and Varuna varieties', 'Apply sulfur 40kg/ha for yield'], waterRequirement: 'low', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 5, max: 30 }, rainfall: { min: 200, max: 500 } },
  { crop: 'Wheat', season: 'rabi', region: 'Rajasthan', state: 'Rajasthan', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'March', harvestingEnd: 'April', duration: 130, growingTips: ['Termal heat tolerant varieties', 'RAJ-3765 and HI-1544 varieties', 'Limited irrigation - sprinkler recommended'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 8, max: 34 }, rainfall: { min: 200, max: 400 } },
  { crop: 'Wheat', season: 'rabi', region: 'Rajasthan', state: 'Rajasthan', sowingStart: 'November', sowingEnd: 'November', harvestingStart: 'April', harvestingEnd: 'May', duration: 155, growingTips: ['Use HD-3086 for irrigated areas', 'Proper weed management needed', 'Apply potash for heat tolerance'], waterRequirement: 'medium', soilType: ['Loam', 'Clay loam'], temperature: { min: 5, max: 35 }, rainfall: { min: 300, max: 600 } },
  { crop: 'Guar (Cluster Bean)', season: 'kharif', region: 'Rajasthan', state: 'Rajasthan', sowingStart: 'July', sowingEnd: 'August', harvestingStart: 'October', harvestingEnd: 'November', duration: 100, growingTips: ['RGC-1033 and RGC-1002 varieties', 'Important for gum industry', 'Low input requirement'], waterRequirement: 'low', soilType: ['Sandy', 'Sandy loam'], temperature: { min: 20, max: 42 }, rainfall: { min: 150, max: 400 } },
  { crop: 'Gram (Chickpea)', season: 'rabi', region: 'Rajasthan', state: 'Rajasthan', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 125, growingTips: ['RSG-888 and GNG-2171 varieties', 'Seed treatment with Rhizobium', 'Avoid heavy irrigation'], waterRequirement: 'low', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 10, max: 30 }, rainfall: { min: 200, max: 400 } },

  // MADHYA PRADESH
  { crop: 'Soybean', season: 'kharif', region: 'Malwa', state: 'Madhya Pradesh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 110, growingTips: ['JS-9560 and JS-335 varieties', 'Seed treatment with Bradyrhizobium', 'Moisture conservation practices'], waterRequirement: 'medium', soilType: ['Deep black', 'Medium black'], temperature: { min: 20, max: 38 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Wheat', season: 'rabi', region: 'Vindhya', state: 'Madhya Pradesh', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'March', harvestingEnd: 'April', duration: 130, growingTips: ['MP-4010 and JW-3211 varieties', 'Zero tillage after soybean harvest', '4-5 irrigations sufficient'], waterRequirement: 'medium', soilType: ['Black clay', 'Sandy loam'], temperature: { min: 10, max: 34 }, rainfall: { min: 300, max: 600 } },
  { crop: 'Gram (Chickpea)', season: 'rabi', region: 'Malwa', state: 'Madhya Pradesh', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'March', harvestingEnd: 'April', duration: 150, growingTips: ['JG-11 and JG-130 varieties', 'Line sowing at 30x10cm', 'Wilt management with Trichoderma'], waterRequirement: 'low', soilType: ['Black cotton', 'Sandy loam'], temperature: { min: 10, max: 32 }, rainfall: { min: 300, max: 600 } },
  { crop: 'Cotton', season: 'kharif', region: 'Nimar', state: 'Madhya Pradesh', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'November', harvestingEnd: 'January', duration: 210, growingTips: ['Bt cotton hybrids popular', 'Fertigation through drip', 'NBH-111 variety for region'], waterRequirement: 'medium', soilType: ['Medium black', 'Deep black'], temperature: { min: 22, max: 42 }, rainfall: { min: 500, max: 900 } },
  { crop: 'Paddy (Rice)', season: 'kharif', region: 'Bastar', state: 'Madhya Pradesh', sowingStart: 'June', sowingEnd: 'August', harvestingStart: 'November', harvestingEnd: 'December', duration: 130, growingTips: ['Rainfed rice - traditional varieties', 'Dapog nursery method', 'Aerobic rice in limited water areas'], waterRequirement: 'high', soilType: ['Clay loam', 'Sandy loam'], temperature: { min: 20, max: 38 }, rainfall: { min: 1000, max: 1500 } },
  { crop: 'Maize', season: 'rabi', region: 'Malwa', state: 'Madhya Pradesh', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingStart: 'February', harvestingEnd: 'March', duration: 120, growingTips: ['JM-8 and JM-216 varieties', 'Spring maize also profitable', 'Line sowing recommended'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Black soil'], temperature: { min: 15, max: 32 }, rainfall: { min: 200, max: 400 } },

  // WEST BENGAL
  { crop: 'Rice', season: 'kharif', region: 'Gangetic Delta', state: 'West Bengal', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'December', duration: 135, growingTips: ['Swarna and Khitish varieties', 'Aman season - main kharif crop', 'Heavy rainfall - drainage critical'], waterRequirement: 'high', soilType: ['Alluvial clay', 'Deltaic alluvium'], temperature: { min: 20, max: 36 }, rainfall: { min: 1200, max: 2000 } },
  { crop: 'Rice', season: 'rabi', region: 'Gangetic Delta', state: 'West Bengal', sowingStart: 'December', sowingEnd: 'January', harvestingStart: 'April', harvestingEnd: 'May', duration: 140, growingTips: ['Boro season - summer rice', 'Irrigation intensive', 'HYV varieties recommended'], waterRequirement: 'high', soilType: ['Alluvial clay'], temperature: { min: 15, max: 35 }, rainfall: { min: 100, max: 300 } },
  { crop: 'Jute', season: 'kharif', region: 'West Bengal', state: 'West Bengal', sowingStart: 'March', sowingEnd: 'April', harvestingStart: 'June', harvestingEnd: 'August', duration: 120, growingTips: ['JRO-524 and JRC-321 varieties', 'Retting in clean water for best fiber', 'De-seeding after harvest'], waterRequirement: 'high', soilType: ['Alluvial loam', 'Clay loam'], temperature: { min: 22, max: 38 }, rainfall: { min: 1000, max: 1500 } },
  { crop: 'Potato', season: 'rabi', region: 'West Bengal', state: 'West Bengal', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'January', harvestingEnd: 'February', duration: 90, growingTips: ['Kufri Jyoti and Kufri Chandramukhi', 'Seed treatment before planting', 'Earthing up at 30 days'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 10, max: 28 }, rainfall: { min: 200, max: 400 } },
  { crop: 'Mustard', season: 'rabi', region: 'West Bengal', state: 'West Bengal', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 120, growingTips: ['B-9 and Sanjukta varieties', 'Area under mustard increasing', 'Line sowing at 30cm spacing'], waterRequirement: 'low', soilType: ['Sandy loam', 'Alluvial'], temperature: { min: 8, max: 30 }, rainfall: { min: 200, max: 400 } },
  { crop: 'Tea', season: 'all', region: 'Darjeeling', state: 'West Bengal', sowingStart: 'June', sowingEnd: 'August', harvestingStart: 'March', harvestingEnd: 'November', duration: 365, growingTips: ['Darjeeling tea GI tagged', 'Plucking every 7-10 days in season', 'Organic certification valuable'], waterRequirement: 'medium', soilType: ['Well-drained acidic loam'], temperature: { min: 10, max: 32 }, rainfall: { min: 2000, max: 4000 } },

  // GUJARAT
  { crop: 'Cotton', season: 'kharif', region: 'Saurashtra', state: 'Gujarat', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'November', harvestingEnd: 'January', duration: 200, growingTips: ['Bt cotton widely grown', 'V-797 and Vikram varieties', 'Earliness due to shorter variety'], waterRequirement: 'medium', soilType: ['Black clay', 'Medium black'], temperature: { min: 22, max: 42 }, rainfall: { min: 400, max: 800 } },
  { crop: 'Groundnut', season: 'kharif', region: 'Saurashtra', state: 'Gujarat', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 105, growingTips: ['GG-20 and TG-37A varieties', 'Gypsum application at 35-40 days', 'Two-three irrigations needed'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Red sandy'], temperature: { min: 22, max: 38 }, rainfall: { min: 400, max: 700 } },
  { crop: 'Tobacco', season: 'kharif', region: 'Central Gujarat', state: 'Gujarat', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'November', harvestingEnd: 'December', duration: 150, growingTips: ['GT-9 and ABT-10 varieties', 'Well-drained sandy loam best', 'Shade drying for flue-cured Virginia'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 18, max: 38 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Sugarcane', season: 'kharif', region: 'Surat', state: 'Gujarat', sowingStart: 'January', sowingEnd: 'February', harvestingStart: 'January', harvestingEnd: 'February', duration: 365, growingTips: ['Co-86032 and CoN-05071', 'Drip irrigation in water-scarce areas', 'Gur making is profitable'], waterRequirement: 'high', soilType: ['Black deep soil', 'Clay loam'], temperature: { min: 18, max: 40 }, rainfall: { min: 800, max: 1200 } },
  { crop: 'Wheat', season: 'rabi', region: 'Central Gujarat', state: 'Gujarat', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 115, growingTips: ['GW-173 and GW-322 varieties', 'Early maturing 115 day varieties', 'Limited irrigation in 2-3 splits'], waterRequirement: 'medium', soilType: ['Clay loam', 'Sandy loam'], temperature: { min: 12, max: 34 }, rainfall: { min: 100, max: 300 } },

  // BIHAR
  { crop: 'Rice', season: 'kharif', region: 'North Bihar', state: 'Bihar', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 130, growingTips: ['Rajendra Sweta and Rajendra Mahsuri', 'Flood prone area - flood tolerant varieties', 'System of Rice Intensification'], waterRequirement: 'high', soilType: ['Alluvial clay', 'Sandy loam'], temperature: { min: 22, max: 38 }, rainfall: { min: 1000, max: 1600 } },
  { crop: 'Wheat', season: 'rabi', region: 'South Bihar', state: 'Bihar', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'March', harvestingEnd: 'April', duration: 135, growingTips: ['HD-2733 and PBW-373 varieties', 'Zero tillage after rice', 'Proper weed management'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 8, max: 32 }, rainfall: { min: 200, max: 500 } },
  { crop: 'Maize', season: 'rabi', region: 'South Bihar', state: 'Bihar', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 140, growingTips: ['Bihar famous for maize production', 'Pioneer and DKC hybrids', 'Stagger planting for continuous supply'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 15, max: 32 }, rainfall: { min: 200, max: 500 } },
  { crop: 'Litchi', season: 'all', region: 'Muzaffarpur', state: 'Bihar', sowingStart: 'June', sowingEnd: 'August', harvestingStart: 'May', harvestingEnd: 'June', duration: 365, growingTips: ['Shahi and China varieties famous', 'Pruning after harvest essential', 'Bird netting during fruiting'], waterRequirement: 'medium', soilType: ['Well-drained sandy loam'], temperature: { min: 10, max: 38 }, rainfall: { min: 800, max: 1200 } },
  { crop: 'Makhana (Fox Nut)', season: 'kharif', region: 'North Bihar', state: 'Bihar', sowingStart: 'March', sowingEnd: 'April', harvestingStart: 'September', harvestingEnd: 'November', duration: 220, growingTips: ['Grown in pond/tank systems', 'Bihar produces 90% of India\'s Makhana', 'Traditional farming in water bodies'], waterRequirement: 'high', soilType: ['Pond beds', 'Wetland soils'], temperature: { min: 20, max: 38 }, rainfall: { min: 1000, max: 1500 } },

  // ODISHA
  { crop: 'Rice', season: 'kharif', region: 'Coastal Odisha', state: 'Odisha', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'November', harvestingEnd: 'December', duration: 140, growingTips: ['Swarna sub1 - flood tolerant', 'Lalat and Khandagiri varieties', 'Cyclone preparedness for coastal areas'], waterRequirement: 'high', soilType: ['Deltaic alluvium', 'Laterite'], temperature: { min: 20, max: 36 }, rainfall: { min: 1200, max: 2000 } },
  { crop: 'Pulses (Moong/Urd)', season: 'kharif', region: 'Coastal Odisha', state: 'Odisha', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'August', harvestingEnd: 'September', duration: 70, growingTips: ['Short duration 65-70 day varieties', 'Intercrop with paddy in uplands', 'Use of Rhizobium culture'], waterRequirement: 'low', soilType: ['Sandy loam', 'Red laterite'], temperature: { min: 20, max: 38 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Cotton', season: 'kharif', region: 'Western Odisha', state: 'Odisha', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'December', harvestingEnd: 'February', duration: 200, growingTips: ['Bt cotton hybrids', 'Growing in red laterite soils', 'Pest management for bollworms'], waterRequirement: 'medium', soilType: ['Red laterite', 'Mixed red and black'], temperature: { min: 22, max: 40 }, rainfall: { min: 800, max: 1200 } },
  { crop: 'Groundnut', season: 'rabi', region: 'Coastal Odisha', state: 'Odisha', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'March', harvestingEnd: 'April', duration: 135, growingTips: ['Irrigated groundnut', 'Devi and Smruti varieties', 'Apply gypsum at pegging'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Red loam'], temperature: { min: 15, max: 35 }, rainfall: { min: 100, max: 300 } },
  { crop: 'Vegetables', season: 'rabi', region: 'Coastal Odisha', state: 'Odisha', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'January', harvestingEnd: 'March', duration: 100, growingTips: ['Tomato, brinjal, cabbage', 'Mulching for moisture conservation', 'Integrated nutrient management'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 12, max: 32 }, rainfall: { min: 100, max: 300 } },

  // CHHATTISGARH
  { crop: 'Rice', season: 'kharif', region: 'Chhattisgarh Plains', state: 'Chhattisgarh', sowingStart: 'June', sowingEnd: 'August', harvestingStart: 'November', harvestingEnd: 'January', duration: 140, growingTips: ['Chhattisgarh - Rice Bowl of India', 'Kharif rice is main crop', 'Use SRI method for higher yields'], waterRequirement: 'high', soilType: ['Clay loam', 'Red laterite', 'Black soil'], temperature: { min: 20, max: 38 }, rainfall: { min: 1200, max: 1600 } },
  { crop: 'Pigeonpea (Arhar)', season: 'kharif', region: 'Chhattisgarh', state: 'Chhattisgarh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'December', harvestingEnd: 'January', duration: 180, growingTips: ['Hariyana and ICPL-87 varieties', 'Intercrop with upland rice', 'Protect from pod borer'], waterRequirement: 'low', soilType: ['Red sandy loam', 'Laterite'], temperature: { min: 18, max: 38 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Groundnut', season: 'kharif', region: 'Bastar', state: 'Chhattisgarh', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 105, growingTips: ['Bastar region suitable', 'Rainfed cultivation', 'Farmers practice traditional methods'], waterRequirement: 'medium', soilType: ['Red sandy loam', 'Laterite'], temperature: { min: 20, max: 36 }, rainfall: { min: 800, max: 1200 } },

  // JHARKHAND
  { crop: 'Rice', season: 'kharif', region: 'Jharkhand', state: 'Jharkhand', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'December', duration: 135, growingTips: ['Upland rice varieties for slopy fields', 'Bokaro and Vandana varieties', 'Terrace cultivation in hilly areas'], waterRequirement: 'high', soilType: ['Red laterite', 'Sandy loam'], temperature: { min: 20, max: 36 }, rainfall: { min: 1000, max: 1500 } },
  { crop: 'Maize', season: 'kharif', region: 'Jharkhand', state: 'Jharkhand', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 95, growingTips: ['Short duration 90-95 day varieties', 'Intercrop with legumes', 'Conservation agriculture practices'], waterRequirement: 'medium', soilType: ['Red sandy loam', 'Laterite'], temperature: { min: 18, max: 36 }, rainfall: { min: 600, max: 1000 } },
  { crop: 'Vegetables', season: 'rabi', region: 'Jharkhand', state: 'Jharkhand', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'January', harvestingEnd: 'March', duration: 100, growingTips: ['Winter vegetables in rabi season', 'Cabbage, cauliflower, tomato', 'Drip irrigation in hilly areas'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 8, max: 30 }, rainfall: { min: 100, max: 300 } },

  // ASSAM
  { crop: 'Rice', season: 'kharif', region: 'Brahmaputra Valley', state: 'Assam', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'October', harvestingEnd: 'November', duration: 150, growingTips: ['Sali rice - main crop', 'Flood tolerant varieties needed', 'Bhogali Bihu after harvest'], waterRequirement: 'high', soilType: ['Alluvial clay', 'Sandy loam'], temperature: { min: 18, max: 35 }, rainfall: { min: 2000, max: 3000 }, festivals: [{ name: 'Bhogali Bihu', date: 'January 15', description: 'Harvest festival with feasting' }] },
  { crop: 'Rice', season: 'rabi', region: 'Brahmaputra Valley', state: 'Assam', sowingStart: 'November', sowingEnd: 'December', harvestingStart: 'March', harvestingEnd: 'April', duration: 130, growingTips: ['Boro rice - summer season', 'Short duration 130 day varieties', 'Monopoly variety recommended'], waterRequirement: 'high', soilType: ['Alluvial clay'], temperature: { min: 15, max: 35 }, rainfall: { min: 200, max: 500 } },
  { crop: 'Tea', season: 'all', region: 'Assam', state: 'Assam', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'March', harvestingEnd: 'November', duration: 365, growingTips: ['Assam tea - full-bodied strong brew', 'Pruning in November-December', 'Monsoon flush highest quality'], waterRequirement: 'medium', soilType: ['Well-drained acidic loam'], temperature: { min: 12, max: 36 }, rainfall: { min: 2000, max: 3500 } },
  { crop: 'Jute', season: 'kharif', region: 'Assam', state: 'Assam', sowingStart: 'March', sowingEnd: 'April', harvestingStart: 'July', harvestingEnd: 'August', duration: 120, growingTips: ['Assam gives 20% of India\'s jute', 'Warm humid conditions ideal', 'Retting in slow-flowing water best'], waterRequirement: 'high', soilType: ['Alluvial sandy loam', 'Clay loam'], temperature: { min: 20, max: 38 }, rainfall: { min: 1500, max: 2500 } },
  { crop: 'Mustard', season: 'rabi', region: 'Assam', state: 'Assam', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'February', harvestingEnd: 'March', duration: 130, growingTips: ['TS-38 and M-27 varieties', 'Low acreage but growing', 'Line sowing at 45cm'], waterRequirement: 'low', soilType: ['Sandy loam', 'Alluvial'], temperature: { min: 10, max: 30 }, rainfall: { min: 200, max: 400 } },

  // KERALA
  { crop: 'Coconut', season: 'all', region: 'Kerala', state: 'Kerala', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'Year-round', harvestingEnd: 'Year-round', duration: 365, growingTips: ['Kerala - Land of Coconuts', 'Tall variety for copra, Dwarf for tender nut', 'Apply 10kg FYM per palm yearly'], waterRequirement: 'medium', soilType: ['Coastal sandy loam', 'Red laterite'], temperature: { min: 22, max: 38 }, rainfall: { min: 2000, max: 4000 } },
  { crop: 'Rubber', season: 'all', region: 'Kerala', state: 'Kerala', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'Year-round', harvestingEnd: 'Year-round', duration: 365, growingTips: ['RRII-105 and RRIM-600 clones popular', 'Tapping starts at 7th year', 'Apply NPK 10:10:10 per tree'], waterRequirement: 'medium', soilType: ['Well-drained laterite', 'Red loam'], temperature: { min: 20, max: 35 }, rainfall: { min: 2000, max: 4000 } },
  { crop: 'Pepper (Black Pepper)', season: 'all', region: 'Kerala', state: 'Kerala', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'November', harvestingEnd: 'January', duration: 365, growingTips: ['Panniyur and Karimunda varieties', 'Support trees for climbing', 'Vine training essential'], waterRequirement: 'medium', soilType: ['Well-drained laterite', 'Red soil'], temperature: { min: 20, max: 32 }, rainfall: { min: 1500, max: 2500 } },
  { crop: 'Cardamom', season: 'kharif', region: 'Idukki', state: 'Kerala', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'October', harvestingEnd: 'December', duration: 365, growingTips: ['Idukki district major producer', 'Shade management important', 'Organic cardamom premium price'], waterRequirement: 'medium', soilType: ['Well-drained forest loam'], temperature: { min: 12, max: 30 }, rainfall: { min: 1500, max: 3000 } },
  { crop: 'Rice', season: 'kharif', region: 'Palakkad', state: 'Kerala', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'September', harvestingEnd: 'October', duration: 105, growingTips: ['Palakkad - rice bowl of Kerala', 'Virippu season - short duration', 'Kanali and Jyothi varieties'], waterRequirement: 'high', soilType: ['Alluvial clay', 'Sandy loam'], temperature: { min: 22, max: 36 }, rainfall: { min: 1500, max: 2500 } },

  // HIMACHAL PRADESH
  { crop: 'Apple', season: 'kharif', region: 'Shimla', state: 'Himachal Pradesh', sowingStart: 'January', sowingEnd: 'February', harvestingStart: 'August', harvestingEnd: 'October', duration: 365, growingTips: ['Royal Delicious and Red Chief varieties', 'Cold storage for year-round supply', 'High-density planting for early yield'], waterRequirement: 'medium', soilType: ['Well-drained sandy loam'], temperature: { min: -2, max: 28 }, rainfall: { min: 500, max: 1000 } },
  { crop: 'Wheat', season: 'rabi', region: 'Himachal Pradesh', state: 'Himachal Pradesh', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'May', harvestingEnd: 'June', duration: 200, growingTips: ['Long duration due to cold', 'HS-490 and HPW-360 varieties', 'Apply FYM 10t/ha for soil health'], waterRequirement: 'low', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 0, max: 30 }, rainfall: { min: 500, max: 1000 } },
  { crop: 'Maize', season: 'kharif', region: 'Himachal Pradesh', state: 'Himachal Pradesh', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'September', harvestingEnd: 'October', duration: 140, growingTips: ['Kangra and Kullu valley maize', 'Rainfed cultivation', 'Use composite varieties'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 15, max: 30 }, rainfall: { min: 800, max: 1500 } },
  { crop: 'Paddy (Rice)', season: 'kharif', region: 'Kangra', state: 'Himachal Pradesh', sowingStart: 'May', sowingEnd: 'June', harvestingStart: 'September', harvestingEnd: 'October', duration: 130, growingTips: ['Kangra rice - GI tagged', 'Basmati in lower hills', 'Traditional varieties valued'], waterRequirement: 'high', soilType: ['Clay loam', 'Sandy loam'], temperature: { min: 18, max: 32 }, rainfall: { min: 1000, max: 1500 } },

  // UTTARAKHAND
  { crop: 'Rice', season: 'kharif', region: 'Uttarakhand', state: 'Uttarakhand', sowingStart: 'June', sowingEnd: 'July', harvestingStart: 'October', harvestingEnd: 'November', duration: 130, growingTips: ['Govind Bhog and Basmati varieties', 'Terrace rice cultivation in hills', 'Traditional water channels (Guls)'], waterRequirement: 'high', soilType: ['Sandy loam', 'Clay loam'], temperature: { min: 18, max: 35 }, rainfall: { min: 1000, max: 1500 } },
  { crop: 'Wheat', season: 'rabi', region: 'Uttarakhand', state: 'Uttarakhand', sowingStart: 'October', sowingEnd: 'November', harvestingStart: 'April', harvestingEnd: 'May', duration: 180, growingTips: ['Hills - long duration wheat', 'VL-907 and VL-829 varieties', 'Organic farming potential'], waterRequirement: 'low', soilType: ['Sandy loam', 'Loam'], temperature: { min: 0, max: 30 }, rainfall: { min: 400, max: 800 } },
  { crop: 'Vegetables', season: 'kharif', region: 'Uttarakhand', state: 'Uttarakhand', sowingStart: 'March', sowingEnd: 'April', harvestingStart: 'June', harvestingEnd: 'September', duration: 120, growingTips: ['Off-season vegetables off-season premium', 'Tomato, cabbage, capsicum', 'Protected cultivation in tunnels'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 12, max: 30 }, rainfall: { min: 400, max: 800 } },
  { crop: 'Fruits', season: 'kharif', region: 'Uttarakhand', state: 'Uttarakhand', sowingStart: 'January', sowingEnd: 'February', harvestingStart: 'June', harvestingEnd: 'October', duration: 365, growingTips: ['Peach, plum, apricot in hills', 'Mango in foot-hills', 'Horticulture focus state'], waterRequirement: 'medium', soilType: ['Well-drained sandy loam'], temperature: { min: 5, max: 35 }, rainfall: { min: 500, max: 1000 } },

  // ZAID season crops (common across north India)
  { crop: 'Watermelon', season: 'zaid', region: 'North India', state: 'All States', sowingStart: 'February', sowingEnd: 'March', harvestingStart: 'May', harvestingEnd: 'June', duration: 80, growingTips: ['Summer crop - short duration', 'Drip irrigation for quality', 'Fruit bagging for uniform color'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Riverbed'], temperature: { min: 22, max: 40 }, rainfall: { min: 50, max: 200 } },
  { crop: 'Cucumber', season: 'zaid', region: 'North India', state: 'All States', sowingStart: 'February', sowingEnd: 'March', harvestingStart: 'April', harvestingEnd: 'May', duration: 60, growingTips: ['Short duration summer crop', 'Staking for better yield', 'Regular irrigation needed'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 18, max: 35 }, rainfall: { min: 50, max: 200 } },
  { crop: 'Moong (Green Gram)', season: 'zaid', region: 'North India', state: 'All States', sowingStart: 'March', sowingEnd: 'April', harvestingStart: 'May', harvestingEnd: 'June', duration: 65, growingTips: ['Short duration summer pulse', 'SML-668 and IPM-2-3 varieties', 'Residual moisture sufficient'], waterRequirement: 'low', soilType: ['Sandy loam', 'Loam'], temperature: { min: 20, max: 40 }, rainfall: { min: 50, max: 150 } },
  { crop: 'Sunflower', season: 'zaid', region: 'North India', state: 'All States', sowingStart: 'February', sowingEnd: 'March', harvestingStart: 'May', harvestingEnd: 'June', duration: 85, growingTips: ['KBSH-1 and DRSH-1 hybrids', 'Good summer oilseed crop', 'Bee keeping for pollination'], waterRequirement: 'medium', soilType: ['Sandy loam', 'Loam'], temperature: { min: 18, max: 36 }, rainfall: { min: 50, max: 200 } }
];

module.exports = cropCalendar;
