const fertilizers = [
  // Organic fertilizers
  {
    name: 'Farmyard Manure (FYM)',
    type: 'organic',
    nutrientContent: { nitrogen: 0.8, phosphorus: 0.4, potassium: 0.8 },
    suitableCrops: ['All Crops'],
    dosage: { base: '10-15 tons/ha', instructions: 'Apply 2-3 weeks before sowing and mix well with soil during final plowing' },
    application: { method: 'soil', timing: 'Before sowing/planting', frequency: 'Every season' },
    price: { min: 1500, max: 2500, unit: 'ton' },
    rating: 4.5,
    organic: true,
    description: 'Traditional decomposed cow dung and urine mixed with bedding material. Best soil conditioner.',
    precautions: ['Use well-decomposed manure (3-6 months old)', 'Avoid fresh manure as it burns roots', 'Store in shaded area', 'Mix with soil immediately after spreading']
  },
  {
    name: 'Vermicompost',
    type: 'organic',
    nutrientContent: { nitrogen: 1.5, phosphorus: 0.8, potassium: 1.2 },
    suitableCrops: ['Vegetables', 'Fruits', 'Flowers', 'Cash Crops'],
    dosage: { base: '5-8 tons/ha', instructions: 'Apply as basal dressing or top dressing. Mix with topsoil around plants.' },
    application: { method: 'soil', timing: 'At planting and as top dressing', frequency: 'Every 45-60 days' },
    price: { min: 8000, max: 12000, unit: 'ton' },
    rating: 4.7,
    organic: true,
    description: 'Earthworm-processed organic waste rich in humus, enzymes, and beneficial microbes.',
    precautions: ['Keep moist but not wet', 'Store in cool dry place', 'Use within 6 months of production', 'Do not mix with chemical fertilizers directly']
  },
  {
    name: 'Neem Cake',
    type: 'organic',
    nutrientContent: { nitrogen: 5.0, phosphorus: 1.0, potassium: 1.5 },
    suitableCrops: ['Rice', 'Sugarcane', 'Vegetables', 'Cotton', 'Pulses'],
    dosage: { base: '1-2 tons/ha', instructions: 'Apply 15-20 days before sowing. Mix with soil or apply in furrows.' },
    application: { method: 'soil', timing: 'Before sowing', frequency: 'Every season' },
    price: { min: 15000, max: 25000, unit: 'ton' },
    rating: 4.6,
    organic: true,
    description: 'Residue from neem oil extraction. Acts as both fertilizer and natural pesticide.',
    precautions: ['Use aged neem cake (not fresh)', 'Do not exceed recommended dosage', 'Keep dry to prevent fungal growth', 'Best used in combination with FYM']
  },
  {
    name: 'Poultry Manure',
    type: 'organic',
    nutrientContent: { nitrogen: 3.0, phosphorus: 2.5, potassium: 2.0 },
    suitableCrops: ['Vegetables', 'Fruits', 'Leafy Greens', 'Cash Crops'],
    dosage: { base: '5-7 tons/ha', instructions: 'Apply 2-3 weeks before planting. Incorporate into soil immediately.' },
    application: { method: 'soil', timing: 'Before planting', frequency: 'Every 2 seasons' },
    price: { min: 4000, max: 7000, unit: 'ton' },
    rating: 4.3,
    organic: true,
    description: 'Rich in nitrogen and phosphorus. Improves soil structure and microbial activity.',
    precautions: ['Must be well-composted (3-4 months)', 'Fresh manure can burn plant roots', 'Apply in moderation to avoid nitrogen overload', 'Wash hands after handling']
  },
  {
    name: 'Green Manure (Sunn Hemp)',
    type: 'organic',
    nutrientContent: { nitrogen: 2.5, phosphorus: 0.5, potassium: 1.5 },
    suitableCrops: ['Rice', 'Wheat', 'All Cereals'],
    dosage: { base: '25-30 kg seeds/ha', instructions: 'Grow as intercrop for 45-60 days, then plow into soil before flowering' },
    application: { method: 'soil', timing: '45-60 days before main crop sowing', frequency: 'Every season' },
    price: { min: 2000, max: 3000, unit: 'ha' },
    rating: 4.4,
    organic: true,
    description: 'Leguminous crop grown specifically to be incorporated into soil for nitrogen enrichment.',
    precautions: ['Plow before flowering for best results', 'Ensure adequate moisture for decomposition', 'Ideal for sandy loam soils', 'Can be grown as intercrop']
  },
  {
    name: 'Fish Emulsion',
    type: 'organic',
    nutrientContent: { nitrogen: 5.0, phosphorus: 2.0, potassium: 2.0 },
    suitableCrops: ['Leafy Vegetables', 'Tomato', 'Chilli', 'Fruiting Crops'],
    dosage: { base: '5-10ml/L of water', instructions: 'Foliar spray every 2-3 weeks during growing season. Dilute before use.' },
    application: { method: 'foliar', timing: 'During active growth', frequency: 'Every 2-3 weeks' },
    price: { min: 500, max: 800, unit: 'L' },
    rating: 4.2,
    organic: true,
    description: 'Liquid fertilizer made from fish processing waste. Quick-acting nitrogen source.',
    precautions: ['Dilute properly to avoid leaf burn', 'Apply in cool evening hours', 'Has strong odor - store in sealed container', 'Shake well before use']
  },
  {
    name: 'Bone Meal',
    type: 'organic',
    nutrientContent: { nitrogen: 3.0, phosphorus: 12.0, potassium: 0.0 },
    suitableCrops: ['Root Vegetables', 'Fruits', 'Flowers', 'Legumes'],
    dosage: { base: '200-300 g/plant or 1-2 tons/ha', instructions: 'Mix into soil at planting time. Slow release throughout season.' },
    application: { method: 'soil', timing: 'At planting', frequency: 'Every season' },
    price: { min: 12000, max: 18000, unit: 'ton' },
    rating: 4.1,
    organic: true,
    description: 'Steamed animal bones ground into powder. Excellent phosphorus source for root development.',
    precautions: ['Slow-release - apply at least 2 weeks before planting', 'Keep away from pets', 'Store in dry place', 'Wear mask when handling powder']
  },
  {
    name: 'Compost Tea',
    type: 'organic',
    nutrientContent: { nitrogen: 0.5, phosphorus: 0.3, potassium: 0.5 },
    suitableCrops: ['All Crops'],
    dosage: { base: '20-50 L/acre', instructions: 'Apply as soil drench or foliar spray. Dilute 1:10 with water before use.' },
    application: { method: 'foliar', timing: 'Throughout growing season', frequency: 'Every 2 weeks' },
    price: { min: 100, max: 200, unit: 'L' },
    rating: 4.0,
    organic: true,
    description: 'Liquid extract from steeping compost in water. Rich in beneficial microbes and nutrients.',
    precautions: ['Use within 24 hours of brewing', 'Keep aerated before use', 'Do not store for long periods', 'Best applied in early morning']
  },
  // Biofertilizers
  {
    name: 'Rhizobium Culture',
    type: 'biofertilizer',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0 },
    suitableCrops: ['Pulses', 'Soybean', 'Groundnut', 'Legumes', 'Chickpea'],
    dosage: { base: '200 g/10 kg seeds', instructions: 'Mix with water to make slurry. Coat seeds before sowing. Use within 24 hours.' },
    application: { method: 'seed treatment', timing: 'Immediately before sowing', frequency: 'Every season' },
    price: { min: 300, max: 500, unit: 'kg' },
    rating: 4.5,
    organic: true,
    description: 'Nitrogen-fixing bacteria that form nodules on legume roots, fixing atmospheric nitrogen.',
    precautions: ['Do not mix with chemical fertilizers directly', 'Keep in cool place away from sunlight', 'Use before expiry date', 'Use within 24 hours of mixing']
  },
  {
    name: 'Azospirillum',
    type: 'biofertilizer',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0 },
    suitableCrops: ['Rice', 'Wheat', 'Maize', 'Sugarcane', 'Millets'],
    dosage: { base: '200 g/10 kg seeds or 5 L/ha', instructions: 'Seed treatment or soil application with FYM. Apply near root zone.' },
    application: { method: 'seed treatment', timing: 'At sowing', frequency: 'Every season' },
    price: { min: 250, max: 400, unit: 'kg' },
    rating: 4.3,
    organic: true,
    description: 'Free-living nitrogen-fixing bacteria for non-leguminous crops. Enhances root growth.',
    precautions: ['Store at room temperature away from sunlight', 'Do not mix with fungicides', 'Use within 6 hours of mixing', 'Irrigate lightly after application']
  },
  {
    name: 'PSB (Phosphate Solubilizing Bacteria)',
    type: 'biofertilizer',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0 },
    suitableCrops: ['All Crops'],
    dosage: { base: '200 g/10 kg seeds or 5 kg/ha', instructions: 'Seed treatment or soil application. Converts fixed phosphorus to available form.' },
    application: { method: 'seed treatment', timing: 'At sowing', frequency: 'Every season' },
    price: { min: 300, max: 500, unit: 'kg' },
    rating: 4.2,
    organic: true,
    description: 'Beneficial bacteria that solubilize insoluble phosphates in soil, making phosphorus available.',
    precautions: ['Apply near root zone', 'Keep away from direct sunlight', 'Mix with compost for soil application', 'Maintain soil moisture after application']
  },
  {
    name: 'Trichoderma Viride',
    type: 'biofertilizer',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0 },
    suitableCrops: ['All Crops'],
    dosage: { base: '250 g/10 kg seeds or 5 kg/ha with FYM', instructions: 'Seed treatment or soil application. Biocontrol agent.' },
    application: { method: 'seed treatment', timing: 'At sowing', frequency: 'Every season' },
    price: { min: 350, max: 550, unit: 'kg' },
    rating: 4.6,
    organic: true,
    description: 'Fungal biocontrol agent effective against soil-borne diseases like wilt and root rot.',
    precautions: ['Do not mix with chemical fungicides', 'Store in cool dry place', 'Apply in evening', 'Irrigate after soil application']
  },
  // Chemical fertilizers
  {
    name: 'Urea',
    type: 'chemical',
    nutrientContent: { nitrogen: 46, phosphorus: 0, potassium: 0 },
    suitableCrops: ['Rice', 'Wheat', 'Maize', 'Sugarcane', 'All Crops'],
    dosage: { base: '100-150 kg/ha', instructions: 'Split into 2-3 doses. Apply in moist soil and irrigate immediately. Do not apply on dry soil.' },
    application: { method: 'soil', timing: 'After seedling establishment and at growth stages', frequency: 'Split in 2-3 doses per season' },
    price: { min: 6, max: 8, unit: 'kg' },
    rating: 4.0,
    organic: false,
    description: 'Most concentrated nitrogen fertilizer (46% N). White crystalline, highly soluble, rapid acting.',
    precautions: ['Do not mix with alkaline substances', 'Apply 5-7 cm deep in soil to prevent volatilization', 'Irrigate immediately after application', 'Avoid contact with seeds/seedlings']
  },
  {
    name: 'DAP (Diammonium Phosphate)',
    type: 'chemical',
    nutrientContent: { nitrogen: 18, phosphorus: 46, potassium: 0 },
    suitableCrops: ['Wheat', 'Rice', 'Maize', 'Pulses', 'Oilseeds', 'All Crops'],
    dosage: { base: '100-150 kg/ha', instructions: 'Apply as basal dose at sowing/planting. Place 5-7 cm below and beside seeds.' },
    application: { method: 'soil', timing: 'At sowing/planting as basal', frequency: 'Once per season' },
    price: { min: 12, max: 15, unit: 'kg' },
    rating: 4.3,
    organic: false,
    description: 'High phosphorus fertilizer with nitrogen. Essential for root development and early growth.',
    precautions: ['Do not mix with Urea', 'Keep away from seeds (can cause germination damage)', 'Apply in moist soil', 'Store in airtight containers']
  },
  {
    name: 'MOP (Muriate of Potash)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 60 },
    suitableCrops: ['Potato', 'Banana', 'Cotton', 'Sugarcane', 'Tobacco', 'Fruits'],
    dosage: { base: '40-80 kg/ha', instructions: 'Apply as basal or with first top dressing. Mix well with soil.' },
    application: { method: 'soil', timing: 'Basal or early growth stage', frequency: 'Once per season' },
    price: { min: 20, max: 24, unit: 'kg' },
    rating: 4.1,
    organic: false,
    description: 'Most common potassium fertilizer. Improves fruit quality, disease resistance, and water use efficiency.',
    precautions: ['Not suitable for chloride-sensitive crops like tobacco (use SOP instead)', 'Apply before flowering', 'Do not mix with calcium ammonium nitrate', 'Store in dry place']
  },
  {
    name: 'SOP (Sulphate of Potash)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 50, sulfur: 18 },
    suitableCrops: ['Fruits', 'Vegetables', 'Tobacco', 'Potato', 'Grapes', 'Tea'],
    dosage: { base: '30-60 kg/ha', instructions: 'Apply as basal or top dressing. Particularly beneficial for quality crops.' },
    application: { method: 'soil', timing: 'Basal or at early growth', frequency: 'Once per season' },
    price: { min: 25, max: 30, unit: 'kg' },
    rating: 4.4,
    organic: false,
    description: 'Premium potassium source without chloride. Ideal for quality-sensitive crops.',
    precautions: ['More expensive than MOP - use judiciously', 'Best for chloride-sensitive crops', 'Apply before flowering', 'Store in dry moisture-proof container']
  },
  {
    name: 'SSP (Single Super Phosphate)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 16, sulfur: 12, calcium: 20 },
    suitableCrops: ['Pulses', 'Oilseeds', 'Legumes', 'All Crops'],
    dosage: { base: '200-300 kg/ha', instructions: 'Apply as basal dose. Mix thoroughly with soil before sowing.' },
    application: { method: 'soil', timing: 'At sowing/planting', frequency: 'Once per season' },
    price: { min: 7, max: 10, unit: 'kg' },
    rating: 4.0,
    organic: false,
    description: 'Cost-effective phosphorus fertilizer with sulfur and calcium. Suitable for organic farming.',
    precautions: ['Requires higher quantity than DAP', 'Best for acidic soils', 'Mix well with soil', 'Apply before or at sowing']
  },
  {
    name: 'Ammonium Sulphate',
    type: 'chemical',
    nutrientContent: { nitrogen: 21, phosphorus: 0, potassium: 0, sulfur: 24 },
    suitableCrops: ['Rice', 'Tea', 'Potato', 'Onion', 'Garlic', 'Sulfur-loving crops'],
    dosage: { base: '100-200 kg/ha', instructions: 'Apply as top dressing. Works well in alkaline soils.' },
    application: { method: 'soil', timing: 'After seedling establishment', frequency: 'Split into 2 doses' },
    price: { min: 8, max: 12, unit: 'kg' },
    rating: 4.2,
    organic: false,
    description: 'Acidic nitrogen fertilizer with sulfur. Excellent for alkaline soils and sulfur-demanding crops.',
    precautions: ['Increases soil acidity with continuous use', 'Apply in moist soil', 'Do not mix with lime', 'Ideal for alkaline/calcareous soils']
  },
  {
    name: 'NPK 10-26-26 Complex',
    type: 'chemical',
    nutrientContent: { nitrogen: 10, phosphorus: 26, potassium: 26 },
    suitableCrops: ['Pulses', 'Oilseeds', 'Cotton', 'Maize', 'All Crops'],
    dosage: { base: '100-150 kg/ha', instructions: 'Apply as basal dose at sowing. Place 5 cm away from seed.' },
    application: { method: 'soil', timing: 'At sowing/planting', frequency: 'Once per season' },
    price: { min: 18, max: 22, unit: 'kg' },
    rating: 4.3,
    organic: false,
    description: 'Complex fertilizer with balanced NPK. Ideal for crops needing high P and K at early stages.',
    precautions: ['Use as basal dose only', 'Do not exceed recommended dose', 'Store in dry place', 'Check soil test before application']
  },
  {
    name: 'NPK 20-20-0 Complex',
    type: 'chemical',
    nutrientContent: { nitrogen: 20, phosphorus: 20, potassium: 0 },
    suitableCrops: ['Rice', 'Wheat', 'Maize', 'Cotton', 'All Crops'],
    dosage: { base: '100-150 kg/ha', instructions: 'Apply as basal or early top dressing.' },
    application: { method: 'soil', timing: 'At sowing or early growth', frequency: 'Once per season' },
    price: { min: 15, max: 18, unit: 'kg' },
    rating: 4.1,
    organic: false,
    description: 'Balanced N and P fertilizer. Cost-effective for crops with low K requirement or K-rich soils.',
    precautions: ['Supplement with K if soil is potassium-deficient', 'Not for extended use on K-depleted soils', 'Apply as basal dose', 'Use soil test recommendations']
  },
  {
    name: 'NPK 12-32-16 Complex',
    type: 'chemical',
    nutrientContent: { nitrogen: 12, phosphorus: 32, potassium: 16 },
    suitableCrops: ['Cotton', 'Vegetables', 'Fruits', 'Sugarcane', 'Potato'],
    dosage: { base: '100-150 kg/ha', instructions: 'Apply as basal dose at planting time.' },
    application: { method: 'soil', timing: 'At planting', frequency: 'Once' },
    price: { min: 20, max: 25, unit: 'kg' },
    rating: 4.4,
    organic: false,
    description: 'High phosphorus complex fertilizer for root and fruit development.',
    precautions: ['Apply close to root zone', 'Ideal for P-deficient soils', 'Must be supplemented with later N application', 'Store in dry cool place']
  },
  {
    name: 'Potassium Nitrate (13-0-45)',
    type: 'chemical',
    nutrientContent: { nitrogen: 13, phosphorus: 0, potassium: 45 },
    suitableCrops: ['Fruits', 'Vegetables', 'Cotton', 'Tobacco', 'All high-value crops'],
    dosage: { base: '5-10 g/L for foliar spray', instructions: 'Foliar spray during fruiting/development stage. 2-3 sprays at 15-day intervals.' },
    application: { method: 'foliar', timing: 'During fruiting/development', frequency: '2-3 sprays per season' },
    price: { min: 35, max: 45, unit: 'kg' },
    rating: 4.5,
    organic: false,
    description: 'Premium water-soluble fertilizer for fertigation and foliar application. Free of chloride.',
    precautions: ['Dissolve completely before spraying', 'Apply in cool hours (evening)', 'Do not mix with calcium fertilizers', 'Store in dry sealed packaging']
  },
  {
    name: 'Mono Ammonium Phosphate (MAP)',
    type: 'chemical',
    nutrientContent: { nitrogen: 11, phosphorus: 52, potassium: 0 },
    suitableCrops: ['All Crops'],
    dosage: { base: '50-100 kg/ha', instructions: 'Apply as starter fertilizer at sowing. High phosphorus concentration.' },
    application: { method: 'soil', timing: 'At sowing as starter', frequency: 'Once' },
    price: { min: 28, max: 35, unit: 'kg' },
    rating: 4.2,
    organic: false,
    description: 'Highest phosphorus content among NPK fertilizers. Excellent for P-deficient soils.',
    precautions: ['Do not exceed 100 kg/ha', 'Keep away from seed row', 'Use based on soil test', 'Supplement with N and K as needed']
  },
  {
    name: 'Calcium Nitrate (15.5-0-0)',
    type: 'chemical',
    nutrientContent: { nitrogen: 15.5, phosphorus: 0, potassium: 0, calcium: 19 },
    suitableCrops: ['Fruits', 'Vegetables', 'Tomato', 'Chilli', 'Leafy Greens'],
    dosage: { base: '5-10 g/L foliar or 50-100 kg/ha', instructions: 'Foliar spray or soil application. Corrects calcium deficiency.' },
    application: { method: 'foliar', timing: 'During active growth', frequency: '2-3 sprays per season' },
    price: { min: 30, max: 38, unit: 'kg' },
    rating: 4.3,
    organic: false,
    description: 'Fast-acting nitrogen with calcium. Prevents blossom end rot in tomato and bitter pit in fruits.',
    precautions: ['Highly hygroscopic - store in airtight container', 'Do not mix with sulfates/phosphates', 'Apply in cool weather', 'Use immediately after opening']
  },
  {
    name: 'Zinc Sulphate (21% Zn)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0, zinc: 21 },
    suitableCrops: ['Rice', 'Maize', 'Wheat', 'Citrus', 'All Crops'],
    dosage: { base: '10-25 kg/ha or 3-5 g/L foliar', instructions: 'Soil application mixed with sand. Foliar spray for quick correction.' },
    application: { method: 'foliar', timing: 'At early growth stage', frequency: 'Once or as needed' },
    price: { min: 55, max: 65, unit: 'kg' },
    rating: 4.4,
    organic: false,
    description: 'Essential micronutrient for plant growth. Corrects zinc deficiency (common in rice).',
    precautions: ['Mix with lime (half quantity) for soil application', 'Foliar spray more effective', 'Do not exceed recommended dose', 'Apply at early growth stages']
  },
  {
    name: 'NPK 19-19-19 (Water Soluble)',
    type: 'chemical',
    nutrientContent: { nitrogen: 19, phosphorus: 19, potassium: 19 },
    suitableCrops: ['All Crops - especially fertigation'],
    dosage: { base: '5-10 g/L', instructions: 'Dissolve in water and apply through drip/foliar. Use at all growth stages.' },
    application: { method: 'drip', timing: 'Throughout growth', frequency: 'Every 7-10 days' },
    price: { min: 40, max: 50, unit: 'kg' },
    rating: 4.5,
    organic: false,
    description: 'Completely water-soluble balanced NPK. Ideal for drip irrigation and hydroponics.',
    precautions: ['Dissolve completely before use', 'Check EC of final solution', 'Use filtered water for best results', 'Store in dry place away from moisture']
  },
  {
    name: 'Boron 20% (Solubor)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0, boron: 20 },
    suitableCrops: ['Mustard', 'Cauliflower', 'Sunflower', 'Fruits', 'Groundnut'],
    dosage: { base: '5-10 kg/ha soil or 1-2 g/L foliar', instructions: 'Soil application every 2-3 years. Foliar spray for immediate correction.' },
    application: { method: 'foliar', timing: 'Before flowering', frequency: 'Once or as needed' },
    price: { min: 80, max: 120, unit: 'kg' },
    rating: 4.1,
    organic: false,
    description: 'Essential micronutrient for flowering and fruit set. Prevents hollow heart in groundnut.',
    precautions: ['Toxic in excess - apply carefully', 'Mix thoroughly with soil', 'Foliar spray more effective', 'Do not exceed recommended dose']
  },
  {
    name: 'Ferrous Sulphate (19% Fe)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0, iron: 19 },
    suitableCrops: ['Rice', 'Sugarcane', 'Citrus', 'Groundnut', 'All Crops'],
    dosage: { base: '5-10 g/L foliar or 20-50 kg/ha soil', instructions: 'Foliar spray works best. Soil application with organic matter.' },
    application: { method: 'foliar', timing: 'At chlorosis appearance', frequency: '2-3 sprays' },
    price: { min: 45, max: 55, unit: 'kg' },
    rating: 4.0,
    organic: false,
    description: 'Iron supplement for correcting iron chlorosis (yellowing between veins).',
    precautions: ['Mix with citric acid (5g/L) for better absorption', 'Do not mix with alkaline substances', 'Apply in cool weather', 'Foliar spray more effective than soil']
  },
  {
    name: 'Gypsum (Calcium Sulphate)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0, calcium: 23, sulfur: 19 },
    suitableCrops: ['Groundnut', 'Potato', 'Pulses', 'All Crops'],
    dosage: { base: '200-500 kg/ha', instructions: 'Apply at pegging stage for groundnut. For other crops, apply before sowing.' },
    application: { method: 'soil', timing: 'At pegging (groundnut) or before sowing', frequency: 'Every 1-2 years' },
    price: { min: 4, max: 6, unit: 'kg' },
    rating: 4.3,
    organic: false,
    description: 'Calcium and sulfur source. Improves soil structure in alkaline/sodic soils.',
    precautions: ['Not a substitute for liming on acid soils', 'Apply based on soil test', 'Best for groundnut at flowering', 'Mix with soil for best results']
  },
  {
    name: 'Magnesium Sulphate (Epsom Salt)',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0, magnesium: 9.6, sulfur: 13 },
    suitableCrops: ['Potato', 'Tomato', 'Fruits', 'All Crops'],
    dosage: { base: '5-10 g/L foliar or 20-30 kg/ha soil', instructions: 'Foliar spray for rapid correction. Soil application for long-term.' },
    application: { method: 'foliar', timing: 'When deficiency symptoms appear', frequency: '2-3 sprays' },
    price: { min: 35, max: 45, unit: 'kg' },
    rating: 4.2,
    organic: false,
    description: 'Corrects magnesium deficiency (interveinal chlorosis in older leaves).',
    precautions: ['Highly soluble - dissolves quickly', 'Foliar spray gives faster results', 'Do not mix with calcium fertilizers', 'Store in dry place']
  },
  {
    name: 'Ammonium Phosphate (16-20-0)',
    type: 'chemical',
    nutrientContent: { nitrogen: 16, phosphorus: 20, potassium: 0 },
    suitableCrops: ['Rice', 'Wheat', 'Cotton', 'All Crops'],
    dosage: { base: '100-150 kg/ha', instructions: 'Apply as basal dose at sowing time.' },
    application: { method: 'soil', timing: 'At sowing', frequency: 'Once' },
    price: { min: 14, max: 17, unit: 'kg' },
    rating: 3.9,
    organic: false,
    description: 'Balanced NP alternative to DAP. Good for areas requiring moderate phosphorus.',
    precautions: ['Supplement with K as needed', 'Store in dry place', 'Apply in moist soil', 'Do not exceed 150 kg/ha']
  },
  {
    name: 'NPK 15-15-15 Complex',
    type: 'chemical',
    nutrientContent: { nitrogen: 15, phosphorus: 15, potassium: 15 },
    suitableCrops: ['All Crops'],
    dosage: { base: '80-120 kg/ha', instructions: 'Apply as basal dose. Adjust based on crop requirement.' },
    application: { method: 'soil', timing: 'At sowing/planting', frequency: 'Once per season' },
    price: { min: 16, max: 20, unit: 'kg' },
    rating: 4.2,
    organic: false,
    description: 'All-purpose balanced NPK fertilizer. Reliable for general crop nutrition.',
    precautions: ['Supplement with additional N for high-N crops', 'Use soil test for precise recommendation', 'Store in dry place', 'Apply in moist soil']
  },
  {
    name: 'Calcium Ammonium Nitrate (CAN)',
    type: 'chemical',
    nutrientContent: { nitrogen: 25, phosphorus: 0, potassium: 0, calcium: 8 },
    suitableCrops: ['Cereals', 'Sugarcane', 'Vegetables', 'All Crops'],
    dosage: { base: '80-120 kg/ha', instructions: 'Apply as top dressing. Less acidic than Ammonium Sulphate.' },
    application: { method: 'soil', timing: 'After seedling establishment', frequency: 'Split into 2 doses' },
    price: { min: 10, max: 13, unit: 'kg' },
    rating: 4.1,
    organic: false,
    description: 'Neutral nitrogen fertilizer with calcium. Good for acidic soils.',
    precautions: ['Do not mix with Urea', 'Store in dry place', 'Apply uniformly', 'Irrigate after application']
  },
  {
    name: 'Sulphur 90% WDG',
    type: 'chemical',
    nutrientContent: { nitrogen: 0, phosphorus: 0, potassium: 0, sulfur: 90 },
    suitableCrops: ['All Crops'],
    dosage: { base: '10-20 kg/ha', instructions: 'Apply as soil application or foliar spray. Also acts as fungicide.' },
    application: { method: 'soil', timing: 'At sowing', frequency: 'Once per season' },
    price: { min: 30, max: 40, unit: 'kg' },
    rating: 4.0,
    organic: false,
    description: 'Concentrated sulfur for sulfur-deficient soils. Also controls powdery mildew.',
    precautions: ['Do not apply in very high temperature', 'Keep away from eyes and skin', 'Apply in cool weather', 'Do not mix with copper-based products']
  }
];

module.exports = fertilizers;
